version: 1.0.{build}
image: Visual Studio 2022

environment:
  matrix:
    - nodejs_version: "22"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - npm run test:e2e
